# docker-compose.yml for RAG Application
version: "3"
services:
  chromadb: 
    image: chromadb/chroma
    container_name: chromadb
    environment:
      - discovery.type=single-node
    ports:
      - 9000:8000
    volumes:
      - chromadbdata1:/usr/share/chromadb/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - discovery.type=single-node
    ports:
      - 11434:11434
    volumes:
      - ollamadata1:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      retries: 5

  chatbot:
    build: .
    command:  python3 chat.py
    environment:
      - DEBUG=True
    depends_on:
      chromadb:
        condition:  service_healthy
      ollama:
        condition:  service_healthy
    ports:
      - 8080:8080
    volumes:
      - /usr/app

volumes:
  chromadbdata1:
    driver: local
  ollamadata1:
    driver: local